FROM python:3.8

RUN mkdir -p /opt/sitemon/
WORKDIR /opt/sitemon

COPY setup.py requirements.txt ./
RUN pip install -r requirements.txt

COPY ./sitemon /opt/sitemon/sitemon

RUN python setup.py install
