version: '3'
services:
  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092

  postgres:
    image: postgres
    ports:
      - '6543:5432'
    environment:
      POSTGRES_PASSWORD: password

  httpbin:
    image: kennethreitz/httpbin

  producer:
    build:
      context: .
      dockerfile: Dockerfile-compose
    command: sitemon producer -c /opt/config/producer.yaml
    depends_on:
      - kafka
      - httpbin
    volumes:
      - ./example_config:/opt/config

  consumer:
    build:
      context: .
      dockerfile: Dockerfile-compose
    command: sitemon consumer -c /opt/config/consumer.yaml
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./example_config:/opt/config
