interval: 5
sites:
  - url: 'http://httpbin/anything?match'
    pattern: match
  - url: 'http://httpbin/anything?wontmatch'
    pattern: something
  - url: 'http://httpbin/status/500'

kafka:
  server: 'kafka:9092'
  topic: sitemon